[package]
name = "rust_todo_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

tokio = { version = "1.18.2", features = ["full"] }
waro = "0.3.2"
serde = { version = "1.0.104", features = ["derive"] }
